#!/bin/sh
set -e

DATA_DIR="${RUSTY_HAND_HOME:-/data}"

# ── 1. Check permissions on data directory ──────────────────────────
if [ ! -w "$DATA_DIR" ]; then
    echo "ERROR: $DATA_DIR is not writable by uid $(id -u) ($(whoami))."
    OWNER_UID=$(stat -c '%u' "$DATA_DIR" 2>/dev/null || stat -f '%u' "$DATA_DIR" 2>/dev/null || echo '?')
    echo "  Directory is owned by uid $OWNER_UID."
    echo "  Fix: run 'chown $(id -u):$(id -g) $DATA_DIR' on the host,"
    echo "  or start the container with '--user $OWNER_UID'."
    exit 1
fi

# ── 2. Generate config.toml from environment variables ──────────────
# If no config.toml exists (or RUSTYHAND_FORCE_ENV_CONFIG=1), generate
# one from RUSTYHAND_* env vars. User-mounted config.toml takes priority.

generate_config() {
    CONFIG="$DATA_DIR/config.toml"

    cat > "$CONFIG" <<TOML
# Auto-generated by docker-entrypoint.sh from environment variables.
# To use a custom config, mount a file to /data/config.toml.

api_listen = "${RUSTYHAND_API_LISTEN:-0.0.0.0:4200}"
log_level = "${RUSTYHAND_LOG_LEVEL:-info}"
TOML

    # ── API auth key ──
    if [ -n "$RUSTYHAND_API_KEY" ]; then
        echo "api_key = \"$RUSTYHAND_API_KEY\"" >> "$CONFIG"
    fi

    # ── Usage footer ──
    if [ -n "$RUSTYHAND_USAGE_FOOTER" ]; then
        echo "usage_footer = \"$RUSTYHAND_USAGE_FOOTER\"" >> "$CONFIG"
    fi

    # ── Default model ──
    cat >> "$CONFIG" <<TOML

[default_model]
provider = "${RUSTYHAND_PROVIDER:-anthropic}"
model = "${RUSTYHAND_MODEL:-claude-sonnet-4-20250514}"
api_key_env = "${RUSTYHAND_MODEL_KEY_ENV:-ANTHROPIC_API_KEY}"
TOML
    if [ -n "$RUSTYHAND_MODEL_BASE_URL" ]; then
        echo "base_url = \"$RUSTYHAND_MODEL_BASE_URL\"" >> "$CONFIG"
    fi

    # ── Fallback provider ──
    if [ -n "$RUSTYHAND_FALLBACK_PROVIDER" ]; then
        cat >> "$CONFIG" <<TOML

[[fallback_providers]]
provider = "${RUSTYHAND_FALLBACK_PROVIDER}"
model = "${RUSTYHAND_FALLBACK_MODEL:-}"
api_key_env = "${RUSTYHAND_FALLBACK_KEY_ENV:-}"
TOML
    fi

    # ── Memory ──
    cat >> "$CONFIG" <<TOML

[memory]
decay_rate = ${RUSTYHAND_MEMORY_DECAY:-0.05}
TOML
    if [ -n "$RUSTYHAND_EMBEDDING_PROVIDER" ]; then
        echo "embedding_provider = \"$RUSTYHAND_EMBEDDING_PROVIDER\"" >> "$CONFIG"
    fi
    if [ -n "$RUSTYHAND_EMBEDDING_KEY_ENV" ]; then
        echo "embedding_api_key_env = \"$RUSTYHAND_EMBEDDING_KEY_ENV\"" >> "$CONFIG"
    fi

    # ── Budget ──
    if [ -n "$RUSTYHAND_BUDGET_DAILY" ] || [ -n "$RUSTYHAND_BUDGET_MONTHLY" ] || [ -n "$RUSTYHAND_BUDGET_HOURLY" ]; then
        cat >> "$CONFIG" <<TOML

[budget]
max_hourly_usd = ${RUSTYHAND_BUDGET_HOURLY:-0.0}
max_daily_usd = ${RUSTYHAND_BUDGET_DAILY:-0.0}
max_monthly_usd = ${RUSTYHAND_BUDGET_MONTHLY:-0.0}
TOML
    fi

    # ── Telegram ──
    if [ -n "$TELEGRAM_BOT_TOKEN" ]; then
        cat >> "$CONFIG" <<TOML

[telegram]
bot_token_env = "TELEGRAM_BOT_TOKEN"
TOML
        if [ -n "$RUSTYHAND_TELEGRAM_USERS" ]; then
            echo "allowed_users = [$RUSTYHAND_TELEGRAM_USERS]" >> "$CONFIG"
        fi
    fi

    # ── Discord ──
    if [ -n "$DISCORD_BOT_TOKEN" ]; then
        cat >> "$CONFIG" <<TOML

[discord]
bot_token_env = "DISCORD_BOT_TOKEN"
TOML
    fi

    # ── Slack ──
    if [ -n "$SLACK_BOT_TOKEN" ]; then
        cat >> "$CONFIG" <<TOML

[slack]
bot_token_env = "SLACK_BOT_TOKEN"
TOML
        if [ -n "$SLACK_APP_TOKEN" ]; then
            echo "app_token_env = \"SLACK_APP_TOKEN\"" >> "$CONFIG"
        fi
    fi

    # ── Exec policy ──
    if [ -n "$RUSTYHAND_EXEC_MODE" ]; then
        cat >> "$CONFIG" <<TOML

[exec_policy]
mode = "${RUSTYHAND_EXEC_MODE}"
TOML
    fi

    # ── A2A ──
    if [ "$RUSTYHAND_A2A_ENABLED" = "true" ] || [ "$RUSTYHAND_A2A_ENABLED" = "1" ]; then
        cat >> "$CONFIG" <<TOML

[a2a]
enabled = true
TOML
    fi

    echo "Generated config from environment variables at $CONFIG"
}

if [ "$RUSTYHAND_FORCE_ENV_CONFIG" = "1" ] || [ ! -f "$DATA_DIR/config.toml" ]; then
    generate_config
fi

# ── 3. Check that at least one LLM API key is set ──────────────────
HAS_KEY=0
for VAR in ANTHROPIC_API_KEY KIMI_API_KEY DEEPSEEK_API_KEY ZHIPU_API_KEY \
           MINIMAX_API_KEY OPENROUTER_API_KEY; do
    eval "val=\$$VAR"
    if [ -n "$val" ]; then
        HAS_KEY=1
        break
    fi
done

if [ "$HAS_KEY" = "0" ]; then
    echo "WARNING: No LLM API key found. Set at least one of:"
    echo "  ANTHROPIC_API_KEY, KIMI_API_KEY, DEEPSEEK_API_KEY, ZHIPU_API_KEY,"
    echo "  MINIMAX_API_KEY, OPENROUTER_API_KEY"
    echo "  (Ollama needs no key — just run it locally on localhost:11434)"
fi

# ── 4. Exec into rustyhand ──────────────────────────────────────────
exec rustyhand "$@"
